name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RSYNC_SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.RSYNC_SERVER_PORT }} ${{ secrets.RSYNC_SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy with rsync
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.RSYNC_SERVER_PORT }} -i ~/.ssh/deploy_key" \
            dist/ ${{ secrets.RSYNC_USERNAME }}@${{ secrets.RSYNC_SERVER_HOST }}:${{ secrets.RSYNC_SERVER_DESTINATION }}
